export const categories = [
    'Fiction',
    'Non-Fiction',
    'Juvenile Fiction',
    'Juvenile Non-Fiction',
    'Art',
    'Biography',
    'Autobiography',
    'Business',
    'Economics',
    'Cooking',
    'Education',
    'Health',
    'Fitness',
    'History',
    'House & Home',
    'Law',
    'Literature',
    'Mathematics',
    'Medical',
    'Music',
    'Nature',
    'Philosophy',
    'Psychology',
    'Religion',
    'Science',
    'Social Science',
    'Sports',
    'Recreation',
    'Technology',
    'Travel',
    'Poetry',
    'Drama',
    'Computers',
  ];